#
# Makefile for the Linux kernel sunlight supplied third-party device drivers.
#

#
# NOTE: to allow drivers to be added and removed without causing merge
# collisions you should add new entries in the middle of the six lines
# of ## at the bottom of the list.  Always add three lines of ## above
# your new entry and maintain the six lines below.
#

##
##
##
##
##
##
##
##
##
obj-$(CONFIG_SUNLIGHT_HOST)      += sunlight-host/
##
##
##
##
##
##

# This is a stupid trick to get kbuild to create sunlight/built-in.o
obj- += foo.o
